AR-871: Added --update --cleanup-regions to prod script
os2display/display-docker-server pull request #4
Opened 2022-11-21 11:34 UTC by tuj

2022-11-23 19:01 UTC, sinejespersen approved these changes

2022-11-24 08:23 UTC, turegjorup requested changes
Why only change the `restart-prod.sh` script? Is this not needed for `dev/stg`?

2022-11-24 08:23 UTC, turegjorup commented on restart-prod.sh
> +docker-compose --env-file .env.docker.local -f docker-compose.server.yml exec --user deploy api bin/console app:screen-layouts:load --update --cleanup-regions https://raw.githubusercontent.com/os2dis
Shouldn't these link to `main`?

2023-01-09 10:32 UTC, tuj commented on restart-prod.sh
> +docker-compose --env-file .env.docker.local -f docker-compose.server.yml exec --user deploy api bin/console app:screen-layouts:load --update --cleanup-regions https://raw.githubusercontent.com/os2dis
Fixed

2023-01-09 10:33 UTC, tuj commented
The restart_develop script has been updated in another PR

2023-01-10 10:09 UTC, turegjorup approved these changes

2023-01-11 08:18 UTC, merged